title: Hans Subteniente
description: Turning data into insights | Data Science with Python, R, Tableau, Spark & Power BI | Automation & Azure Fundamentals certified
show_downloads: true
theme: jekyll-theme-minimal
